---
name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go_version: [1.11.x, 1.12.x, 1.13.x]

    name: Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - uses: actions/checkout@v1

      - name: Download Go modules
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: Run linter
        uses: docker://golangci/golangci-lint
        env:
          GOROOT: /usr/local/go
        with:
          entrypoint: golangci-lint
          args: run --enable-all -D lll -D errcheck

      - name: Run tests
        run: go test -mod readonly -race
